/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudproductos;

/**
 *
 * @author PC-04
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        
        
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JDesktopPane();
        mnuGestion = new javax.swing.JMenuBar();
        mnuGestionProducto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuGestionCategoria = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        mnuGestionProducto.setText("PRODUCTOS");
        mnuGestionProducto.addActionListener(this::mnuGestionProductoActionPerformed);

        jMenuItem1.setText("Gestion De Productos");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        mnuGestionProducto.add(jMenuItem1);

        mnuGestion.add(mnuGestionProducto);

        mnuGestionCategoria.setText("CATEGORIA");
        mnuGestion.add(mnuGestionCategoria);

        mnuSalir.setText("SALIR");
        mnuGestion.add(mnuSalir);

        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuGestion.add(mnuCerrarSesion);

        setJMenuBar(mnuGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionProductoActionPerformed
            FrmProductos frm = new FrmProductos();
            dskPrincipal.add(frm);
            frm.pack();
            int x = (dskPrincipal.getWidth() - frm.getWidth()) / 2;
            int y = (dskPrincipal.getHeight() - frm.getHeight()) / 2;
            frm.setLocation(
            Math.max(0, x),
            Math.max(0, y)
            );
        frm.setVisible(true);
    }//GEN-LAST:event_mnuGestionProductoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmProductos frm = new FrmProductos();
        dskPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }
    
    private void abrirProductos() {
 for (javax.swing.JInternalFrame frame : dskPrincipal.getAllFrames()) {
 if (frame instanceof FrmProductos) {
 try {
 frame.setIcon(false);
 frame.setSelected(true);
 } catch (java.beans.PropertyVetoException e) {
 }
 frame.toFront();
 return;
 }
 }
 FrmProductos frm = new FrmProductos();
 dskPrincipal.add(frm);
 frm.pack();
 int x = (dskPrincipal.getWidth() - frm.getWidth()) / 2;
 int y = (dskPrincipal.getHeight() - frm.getHeight()) / 2;
 frm.setLocation(Math.max(0, x), Math.max(0, y));
 frm.setVisible(true);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenuBar mnuGestion;
    private javax.swing.JMenu mnuGestionCategoria;
    private javax.swing.JMenu mnuGestionProducto;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
