/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.crudproductos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC-04
 */
public class FrmProductos extends javax.swing.JInternalFrame {
    
    private Map<String, Integer> categorias = new HashMap<>();

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        txtId.setEnabled(false);
        tblProductos.setSelectionMode(
        ListSelectionModel.SINGLE_SELECTION
        );
        cargarCategorias();
        listarProductos();
        estadoInicial();
        
    }
    
    private void habilitarCampos(boolean estado) {
 txtNombre.setEnabled(estado);
 cboCategoria.setEnabled(estado);
 txtPrecio.setEnabled(estado);
 txtStock.setEnabled(estado);
}
    private void estadoInicial() {
        habilitarCampos(false);
 btnNuevo.setEnabled(true);
 btnGuardar.setEnabled(false);
 btnActualizar.setEnabled(false);
 btnEliminar.setEnabled(false);
 btnCancelar.setEnabled(false);

    }
    private void estadoNuevo() {
 habilitarCampos(true);
 btnNuevo.setEnabled(false);
 btnGuardar.setEnabled(true);
 btnActualizar.setEnabled(false);
 btnEliminar.setEnabled(false);
 btnCancelar.setEnabled(true);
}
private void estadoEdicion() {
 habilitarCampos(true);
 btnNuevo.setEnabled(false);
 btnGuardar.setEnabled(false);
 btnActualizar.setEnabled(true);
 btnEliminar.setEnabled(true);
 btnCancelar.setEnabled(true);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Mouse Logitech", "Perifericos",  new Double(69.9),  new Integer(20)},
                { new Integer(2), "Monitor LG 24", "Monitores",  new Double(649.9),  new Integer(8)},
                { new Integer(3), "SSD Kingston 1TB", "Almacenamiento",  new Double(289.9),  new Integer(15)},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Categoria", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel1.setText("Código");

        jLabel2.setText("Producto");

        jLabel3.setText("Categoría");

        txtId.setText("jTextField1");

        txtNombre.setText("jTextField2");
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtPrecio.setText("jTextField3");

        txtStock.setText("jTextField4");
        txtStock.addActionListener(this::txtStockActionPerformed);

        jLabel4.setText("Precio");

        jLabel5.setText("Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarProducto();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    
        accionarNuevo();
    
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        accionarCancelar();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarProducto();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        cargarRegistroSeleccionado();

    }//GEN-LAST:event_tblProductosMouseClicked
    private void cargarCategorias() {
        cboCategoria.removeAllItems();
        categorias.clear();
        
        String sql = "SELECT id_categoria, nombre FROM categoria ORDER BY nombre";
        
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            
            while (rs.next()) {
                int id = rs.getInt("id_categoria");
                String nombre = rs.getString("nombre");
                
                cboCategoria.addItem(nombre);
                categorias.put(nombre, id); // Guarda la relación en el Map
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar categorías: " + e.getMessage());
        }
    }
    
        private void listarProductos() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID", "Producto", "Categoría", "Precio", "Stock"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en la tabla (Sección 9 - Buenas prácticas)
            }
        };

        String sql = "SELECT p.id_producto, p.nombre, c.nombre AS categoria, p.precio, p.stock " +
                     "FROM producto p " +
                     "INNER JOIN categoria c ON p.id_categoria = c.id_categoria " +
                     "ORDER BY p.id_producto";

        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getString("nombre"),
                    rs.getString("categoria"),
                    rs.getDouble("precio"),
                    rs.getInt("stock")
                };
                modelo.addRow(fila);
            }
            tblProductos.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al listar productos: " + e.getMessage());
        }
    }
    // 10.1 Validar campos obligatorios
    private boolean validarCampos() {
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del producto");
            txtNombre.requestFocus();
            return false;
        }
        if (cboCategoria.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría");
            return false;
        }
        if (txtPrecio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el precio");
            txtPrecio.requestFocus();
            return false;
        }
        if (txtStock.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el stock");
            txtStock.requestFocus();
            return false;
        }
        return true;
    }

    // 10.2 Obtener un precio válido
    private Double obtenerPrecioValido() {
        try {
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            if (precio <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor que cero");
                txtPrecio.requestFocus();
                return null;
            }
            return precio;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un precio válido");
            txtPrecio.requestFocus();
            return null;
        }
    }

    // 10.3 Obtener un stock válido
    private Integer obtenerStockValido() {
        try {
            int stock = Integer.parseInt(txtStock.getText().trim());
            if (stock < 0) {
                JOptionPane.showMessageDialog(this, "El stock no puede ser negativo");
                txtStock.requestFocus();
                return null;
            }
            return stock;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un stock válido");
            txtStock.requestFocus();
            return null;
        }
    }
    // 11.1 Limpiar el formulario
    private void limpiar() {
        txtId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        if (cboCategoria.getItemCount() > 0) {
            cboCategoria.setSelectedIndex(0);
        }
        tblProductos.clearSelection();
    }

    // 11.2 Lógica para el botón NUEVO
    private void accionarNuevo() {
        limpiar();
        estadoNuevo();
        txtNombre.requestFocus();
    }

    // 11.3 Lógica para el botón CANCELAR
    private void accionarCancelar() {
        limpiar();
        estadoInicial();
    }
    
        // 12. CREATE: guardar un producto
    private void guardarProducto() {
        // Valida que los campos no estén vacíos
        if (!validarCampos()) {
            return;
        }

        // Valida el formato numérico del precio
        Double precio = obtenerPrecioValido();
        if (precio == null) {
            return;
        }

        // Valida el formato numérico del stock
        Integer stock = obtenerStockValido();
        if (stock == null) {
            return;
        }

        // Obtener los datos del formulario
        String nombre = txtNombre.getText().trim();
        String categoria = cboCategoria.getSelectedItem().toString();
        int idCategoria = categorias.get(categoria); // Recupera el ID correspondiente usando el Map

        String sql = "INSERT INTO producto (nombre, id_categoria, precio, stock) VALUES (?, ?, ?, ?)";

        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) {

            // Asignación de parámetros (?) en orden
            ps.setString(1, nombre);
            ps.setInt(2, idCategoria);
            ps.setDouble(3, precio);
            ps.setInt(4, stock);

            // Ejecuta la inserción en la base de datos
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Producto registrado correctamente");

            // Refresca la interfaz
            listarProductos();
            limpiar();
            estadoInicial();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }
    }
    // 13. Seleccionar un registro del JTable
    private void cargarRegistroSeleccionado() {
        int fila = tblProductos.getSelectedRow();
        
        // Verifica que realmente se haya seleccionado una fila válida
        if (fila >= 0) {
            // Jala los datos de las columnas de la fila seleccionada y los pone en los campos
            txtId.setText(tblProductos.getValueAt(fila, 0).toString());
            txtNombre.setText(tblProductos.getValueAt(fila, 1).toString());
            cboCategoria.setSelectedItem(tblProductos.getValueAt(fila, 2).toString());
            txtPrecio.setText(tblProductos.getValueAt(fila, 3).toString());
            txtStock.setText(tblProductos.getValueAt(fila, 4).toString());
            
            // Cambia la botonera al estado de edición (Sección 6.4)
            estadoEdicion();
        }
    }
//14 update
    private void actualizarProducto() {
        if (txtId.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this,
        "Seleccione un producto");
        return;
        }
        if (!validarCampos()) {
        return;
        }
        Double precio = obtenerPrecioValido();
        if (precio == null) {
        return;
        }
        Integer stock = obtenerStockValido();
        if (stock == null) {
        return;
        }
        int idProducto = Integer.parseInt(txtId.getText());
                String nombre = txtNombre.getText().trim();
                String categoria = cboCategoria.getSelectedItem().toString();
        int idCategoria = categorias.get(categoria);
                String sql =
                            "UPDATE producto SET " +
                            "nombre = ?, id_categoria = ?, " +
                            "precio = ?, stock = ?" +
                            "WHERE id_producto = ?";
            try (Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(sql)) {
                                ps.setString(1, nombre);
                                ps.setInt(2, idCategoria);
                                ps.setDouble(3, precio);
                                ps.setInt(4, stock);
                                ps.setInt(5, idProducto);
                                ps.executeUpdate();
            JOptionPane.showMessageDialog(this,
            "Producto actualizado correctamente");
        listarProductos();
        limpiar();
        estadoInicial();
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                    "Error al actualizar: " + e.getMessage());
 }
}
    
    //15..
    private void eliminarProducto() {
 if (txtId.getText().isEmpty()) {
 JOptionPane.showMessageDialog(this,
 "Seleccione un producto");
 return;
 }
 int respuesta = JOptionPane.showConfirmDialog(
 this,
 "¿Está seguro de eliminar " +
 txtNombre.getText() + "?",
 "Confirmar eliminación",
 JOptionPane.YES_NO_OPTION,
 JOptionPane.WARNING_MESSAGE
 );
 if (respuesta != JOptionPane.YES_OPTION) {
 return;
 }
 String sql =
 "DELETE FROM producto " +
 "WHERE id_producto = ?";
 try (Connection cn = Conexion.conectar();
 PreparedStatement ps = cn.prepareStatement(sql)) {
 int id = Integer.parseInt(txtId.getText());
 ps.setInt(1, id);
 ps.executeUpdate();
 JOptionPane.showMessageDialog(this,
 "Producto eliminado correctamente");
 listarProductos();
 limpiar();
 estadoInicial();
 } catch (SQLException e) {
 JOptionPane.showMessageDialog(this,
 "Error al eliminar: " + e.getMessage());
 }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}

